

# CS 4361 / 5361 - Arrays and NumPy


## **Before you start**

Make a copy of this Colab by clicking on File > Save a Copy in Drive

After making a copy, add your student id, last name, and first name to the title.

In [ ]:
student_name = "Salvador Robles Herrera"
student_id = "80683116"

## Arrays

Arrays are not part of the language. We will use them through the NumPy library. 
Arrays are similar to lists, but all elements must be of the same type.


The NumPy library provides implementations of many useful operations on arrays of any dimensionality.  

The following statement imports the library and declares np as short for NumPy. We can access functions and modules in the NumPy library by using the dot notation. 

In [3]:
import numpy as np

Arrays can be created in several ways.

We can convert a list to a 1-D array.

In [4]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


We can convert a list of lists to a 2-D array (or a list of lists of lists to a 3D array, and so on).

In [5]:
a = np.array([[1,2,3,4],[5,6,7,8]])
print(a)

[[1 2 3 4]
 [5 6 7 8]]


Unlike Java, NumPy does not allow jagged arrays. 

In [6]:
a = np.array([[1,2,3,4],[5,6,7]])
print(a)

[list([1, 2, 3, 4]) list([5, 6, 7])]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  """Entry point for launching an IPython kernel.


The array type is infered from the data provided

In [7]:
a = np.array([[1,2,3,4],[5,6,7,8]])
print(a)

[[1 2 3 4]
 [5 6 7 8]]


In [8]:
a = np.array([[1.5,2,3,4],[5,6,7,8]])
print(a)

[[1.5 2.  3.  4. ]
 [5.  6.  7.  8. ]]


The function zeros creates an array full of zeros; the function ones creates an array full of ones, and the function empty creates an array whose initial content is random and depends on the state of the memory. By default, the dtype of the created array is float64.

In [9]:
a = np.zeros(5) # Create 1-D array
print(a)

[0. 0. 0. 0. 0.]


In [10]:
a = np.zeros((5,3)) # Create 2-D array with 5 rows and 3 colummns
print(a)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [11]:
a = np.ones((2,3)) # Create 2-D array with 2 rows and 3 colummns
print(a)

[[1. 1. 1.]
 [1. 1. 1.]]


You can also specify the type

In [12]:
a = np.ones((2,3),dtype=np.int16) # Create 2-D array with 2 rows and 3 colummns
print(a)

[[1 1 1]
 [1 1 1]]


To create sequences of numbers, NumPy provides the arange function which is analogous to the Python built-in range, but returns an array.

In [13]:
a= np.arange(16)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


In [14]:
a= np.arange(20,100,10)
print(a)

[20 30 40 50 60 70 80 90]


The reshape operation can be used to change the dimensionality of an array (but the number of elements cannot change).

In [15]:
a= np.arange(15)
print(a)
b = a.reshape(5,3)
print(b)
print(b.shape)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]
(5, 3)


In [19]:
a= np.arange(16)
# b = a.reshape(4,5)
# print(b)

reshape returns a copy of the array, without modifying the original array.


In [21]:
a= np.arange(16)
a.reshape(4,4)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


a.shape is a tuple (an immutable list) that contains the size of each of the dimensions of array a. len(a.shape) contains the number of dimensions of a.

In [61]:
a= np.arange(16)
print(a)
print(a.shape)
print(len(a.shape))
b = a.reshape(4,4)
print(b)
print(b.shape)
print(len(b.shape))
c = a.reshape(2,2,4,1)
print(c)
print(c.shape)
print(len(c.shape))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
(16,)
1
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
(4, 4)
2
[[[[ 0]
   [ 1]
   [ 2]
   [ 3]]

  [[ 4]
   [ 5]
   [ 6]
   [ 7]]]


 [[[ 8]
   [ 9]
   [10]
   [11]]

  [[12]
   [13]
   [14]
   [15]]]]
(2, 2, 4, 1)
4


Arithmetic operators on arrays apply elementwise. There's no need to write for loops to perform array operations!!!

In [66]:
a= np.arange(16).reshape(4,4)
print(a)
print(a.shape[-1])
b = a + 5
print(b)
c = a**2
print(c)
d = np.sin(a)
print(d)
print(a+b) 
print(a*c) 

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
4
[[ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]]
[[  0   1   4   9]
 [ 16  25  36  49]
 [ 64  81 100 121]
 [144 169 196 225]]
[[ 0.          0.84147098  0.90929743  0.14112001]
 [-0.7568025  -0.95892427 -0.2794155   0.6569866 ]
 [ 0.98935825  0.41211849 -0.54402111 -0.99999021]
 [-0.53657292  0.42016704  0.99060736  0.65028784]]
[[ 5  7  9 11]
 [13 15 17 19]
 [21 23 25 27]
 [29 31 33 35]]
[[   0    1    8   27]
 [  64  125  216  343]
 [ 512  729 1000 1331]
 [1728 2197 2744 3375]]


Integer indexing works the same was as in Java 

In [30]:
print(a[2,-1])
print(a[0,2])

11
2


As with lists, negative indices (counting from the end) are allowed

In [31]:
print(a[0,-1])
print(a[-1,0])

3
12


Slicing works the same ways as with lists, with one slice per dimension

In [39]:
print(a[1:,1::])  # Select rows 0 and 1 and columns 1,2, and 3

[[ 5  6  7]
 [ 9 10 11]
 [13 14 15]]


In [40]:
print(a[::2,1::2])  # Select rows 0 and 2 and columns 1 and 3

[[ 1  3]
 [ 9 11]]


In [44]:
print(a[:,::-1])  # Reverse the order of columns
print(a[:,::])

[[ 3  2  1  0]
 [ 7  6  5  4]
 [11 10  9  8]
 [15 14 13 12]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [ ]:
print(a[::-1,:])  # Reverse the order of rows

[[12 13 14 15]
 [ 8  9 10 11]
 [ 4  5  6  7]
 [ 0  1  2  3]]


In [46]:
print(a[::-1])  # Reverse the order of rows, trailing ':' may be ommited

[[12 13 14 15]
 [ 8  9 10 11]
 [ 4  5  6  7]
 [ 0  1  2  3]]


We can use lists of the same length as indices

In [59]:
c = a[[2,3,1],[1,0,3]] # Returns 1-D array containing [a[2,1], a[3,0], a[1,3]]
print(a)
print()
print(c)

[[0.10762368 0.65562766 0.30022721 ... 0.93065847 0.09144402 0.13896894]
 [0.53463505 0.54102933 0.50784977 ... 0.90625811 0.2027442  0.48721375]
 [0.44266622 0.61631652 0.49116447 ... 0.33681719 0.37050763 0.7211091 ]
 ...
 [0.09312571 0.46408966 0.9830348  ... 0.32315126 0.28202808 0.70911768]
 [0.95759386 0.0604034  0.54100941 ... 0.25958262 0.22671794 0.876434  ]
 [0.54201126 0.22574379 0.52061223 ... 0.12406241 0.98359304 0.24542165]]

[0.61631652 0.91020196 0.69879388]


We can assign values to array elements and slices

In [55]:
a= np.arange(16).reshape(4,4)
print(a)
a[2,3] = -100
print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[   0    1    2    3]
 [   4    5    6    7]
 [   8    9   10 -100]
 [  12   13   14   15]]


In [56]:
a= np.arange(16).reshape(4,4)
print(a)
a[:2,1:] = -100
print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[   0 -100 -100 -100]
 [   4 -100 -100 -100]
 [   8    9   10   11]
 [  12   13   14   15]]


You can perform elementwise operations on array slices if they are the same size

In [ ]:
a= np.arange(16).reshape(4,4)
print(a)
b = np.arange(6).reshape(2,3)
print(b)
a[:2,1:] = a[:2,1:] - b
print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[0 1 2]
 [3 4 5]]
[[ 0  1  1  1]
 [ 4  2  2  2]
 [ 8  9 10 11]
 [12 13 14 15]]


Warning - arrays are passed by reference; array assignments are shallow

In [ ]:
a= np.arange(16).reshape(4,4)
print(a)
b = a
b[0,0] = 2302
print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[2302    1    2    3]
 [   4    5    6    7]
 [   8    9   10   11]
 [  12   13   14   15]]


This will make a deep copy of a

In [ ]:
a= np.arange(16).reshape(4,4)
print(a)
b = np.copy(a)
b[0,0] = 2302
print(a)
print(b)


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[2302    1    2    3]
 [   4    5    6    7]
 [   8    9   10   11]
 [  12   13   14   15]]


NumPy provides LOTS of array operations. See:
https://numpy.org/doc/stable/reference/routines.math.html

Commonly use built-in functions:


In [ ]:
a = np.array([60,  0, 70, 50, 10, 30, 90, 40, 80, 20])

In [ ]:
print(np.min(a))

0


In [ ]:
print(np.max(a))

90


In [ ]:
print(np.mean(a))

45.0


In [ ]:
print(np.argmax(a)) # Returns the index of the maximum element in a

6


In [ ]:
print(np.argmin(a)) # Returns the index of the minimum element in a

1


Since Python is an interpreted language, loops are slow. See the comparative running time of the same operation with and without loops. 

In [57]:
import time

def sum_array_loops(a,b): 
  c = np.zeros_like(a) 
  for i in range(a.shape[0]):
    for j in range(a.shape[1]):
      c[i,j] =  a[i,j] + b[i,j]
  return c

def sum_array(a,b): 
  c = a +b
  return c
  
size = 2000

a = np.random.random((size,size))
b = np.random.random((size,size))

start = time.time()
c = sum_array_loops(a,b)
elapsed_time1 = time.time() - start
print('elapsed time using loops', elapsed_time1,'secs')

start = time.time()
c = sum_array(a,b)
elapsed_time2 = time.time() - start
print('elapsed time without loops', elapsed_time2,'secs')

print('ratio',elapsed_time1/elapsed_time2)

elapsed time using loops 2.7414419651031494 secs
elapsed time without loops 0.025338172912597656 secs
ratio 108.19414543264708


### Arrays as indices

In addition to slicing, we can use arrays as indices to other arrays. The resulting array will have the shape of the index array.



**Example:**

In [68]:
A = np.arange(0,100,10)
print(A)
index = np.arange(4).reshape(2,2)
print(index)
print(A[index])

[ 0 10 20 30 40 50 60 70 80 90]
[[0 1]
 [2 3]]
[[ 0 10]
 [20 30]]


### Boolean indexing

We can use a boolean array as index. 

In [ ]:
A = np.arange(0,15)
ind = A%3==0
print(A)
print(ind)
print(A[ind])

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
[ True False False  True False False  True False False  True False False
  True False False]
[ 0  3  6  9 12]


### Broadcasting

The term broadcasting describes how NumPy treats arrays with different shapes during arithmetic operations. Subject to certain constraints, the smaller array is “broadcast” (conceptually, it is replicated, but no actual copies are made)  across the larger array so that they have compatible shapes. Broadcasting provides a means of vectorizing array operations so that looping occurs in C instead of Python.

Two dimensions are compatible when they are equal, or one of them is 1

In [69]:
A = np.arange(20).reshape(4,5)
A


array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

Since A and B have the same shape, they are compatible. Thus we can perform arithmetic operations with them.

In [70]:
B = np.random.randint(0,20,size=(4,5))
B

array([[19,  5,  4,  3,  0],
       [15, 15, 10,  8, 13],
       [16, 17, 13, 19,  9],
       [12,  9,  2, 18,  9]])

In [ ]:
A+B

array([[ 8,  2, 13,  9, 23],
       [23, 13, 18, 20, 27],
       [23, 16, 16, 27, 22],
       [33, 29, 21, 25, 26]])

In [ ]:
A*B

array([[  0,   1,  22,  18,  76],
       [ 90,  42,  77,  96, 162],
       [130,  55,  48, 182, 112],
       [270, 208,  68, 126, 133]])

In [ ]:
A==B

array([[False,  True, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False]])

Let the shape of A be (r,c). With broadcasting, we can also perform arithmetic operations with A and arrays of sizes (1,c) and (r,1). 

In [80]:
C = np.arange(5).reshape(1,5)
D = np.arange(4).reshape(4,1)

In [81]:
C

array([[0, 1, 2, 3, 4]])

In [82]:
D

array([[0],
       [1],
       [2],
       [3]])

In [83]:
A * C

array([[ 0,  1,  4,  9, 16],
       [ 0,  6, 14, 24, 36],
       [ 0, 11, 24, 39, 56],
       [ 0, 16, 34, 54, 76]])

In [ ]:
A * D

array([[ 0,  0,  0,  0,  0],
       [ 5,  6,  7,  8,  9],
       [20, 22, 24, 26, 28],
       [45, 48, 51, 54, 57]])

Similarly, we can perform operations on a (r,1) and a (1,c) array and obtain a (r,c) array.

In [ ]:
R = np.arange(5).reshape(-1,1)
C = np.arange(10,17).reshape(1,-1)
print(R)
print(C)
print(R*C)

[[0]
 [1]
 [2]
 [3]
 [4]]
[[10 11 12 13 14 15 16]]
[[ 0  0  0  0  0  0  0]
 [10 11 12 13 14 15 16]
 [20 22 24 26 28 30 32]
 [30 33 36 39 42 45 48]
 [40 44 48 52 56 60 64]]


## **Exercises**


Write the function is_square(a) that receives an array a and determines if a is square (that is, it has exactly two dimensions and they have the same size).


In [24]:
def is_square(a):
  # Your code goes here
  if len(a.shape) == 1:
    return False
  if len(a.shape) == 2:
    return a.shape[0] == a.shape[1] # Feel free to change / remove this line
  return False

In [25]:
a = np.arange(16)
print(a.shape)
print(a)
print(is_square(a))
b = a.reshape(2,8)
print(b)
print(is_square(b))
c = a.reshape(4,4,1)
print(c)
print(is_square(c))
d = a.reshape(4,4)
print(d)
print(is_square(d))

(16,)
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
False
[[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]]
False
[[[ 0]
  [ 1]
  [ 2]
  [ 3]]

 [[ 4]
  [ 5]
  [ 6]
  [ 7]]

 [[ 8]
  [ 9]
  [10]
  [11]]

 [[12]
  [13]
  [14]
  [15]]]
False
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
True


Write the function replace_max(a,m) that replace the maximum element in a by m. If the maximum occurs multiple times, replace only the first occurrence.

In [30]:
def  replace_max(a,m):
  # Your code goes here
  a[np.argmax(a)] = m
  return # Feel free to change / remove this line

In [32]:
a = np.array([20, 90, 80, 70, 40,  0, 50, 60, 30, 10])
print(a)
replace_max(a,-1)
print(a)

[20 90 80 70 40  0 50 60 30 10]
[20 -1 80 70 40  0 50 60 30 10]


Write the function diagonal(a) that receives a square array a and returns a 1D array containing the elements in the diagonal of a (that is [a[0,0], a[1,1], ...).

In [42]:
def diagonal(a):
  # Your code goes here
  #Note you can do: a.diagonal()
  b = np.zeros(len(a), dtype = np.int16)
  for i in range(len(a)):
    b[i] = a[i,i] 
  return b# Feel free to change / remove this line

In [43]:
a = np.array([[10, 70, 40], [ 0, 80, 60], [50, 30, 20]])
print(a.diagonal())
print(len(a))
print(diagonal(a))

[10 80 20]
3
[10 80 20]


## Submission Instructions

1. File > Download .ipynb
2. Go to Blackboard, find the submission page, and upload the .ipynb file you just downloaded.